corrections:
  incoming_flux: true    # fi 보정
  pressure: true         # fp 보정  
  humidity: true         # fw 보정
  biomass: false         # fb 보정 (추후 구현)

calibration:
  optimization_method: "Nelder-Mead"
  initial_N0: 1000
  weighting_method: "Schron_2017"  # or "Kohli_2015"
  default_start_date: "2024-09-15"  # 캘리브레이션 시작일
  default_end_date: "2024-10-10"    # 캘리브레이션 종료일
  
calculation:
  default_start_date: null  # "2024-09-01"
  default_end_date: null    # "2024-09-07"
  exclude_periods:
    months: [11, 12, 1, 2]
    custom_dates: []  # ["2024-01-01:2024-01-31", "2024-06-15:2024-06-20"]
  
  smoothing:
    enabled: false
    method: "savitzky_golay"
    window: 11
    order: 3

validation:
  metrics: ["R2", "RMSE", "MAE", "NSE"]  # Nash-Sutcliffe Efficiency 추가
  
visualization:
  style: "modern"  # modern, classic, publication
  dpi: 300
  figure_size: [15, 7]
  color_palette: "Set2"
  
  plots:
    raw_neutron_timeseries: true
    corrected_neutron_timeseries: true
    correction_factors: true
    soil_moisture_timeseries: true
    sensing_depth_timeseries: true
    validation_scatter: true
    validation_timeseries: true
    correlation_matrix: true

parallel_processing:
  enabled: true
  max_workers: 4
  
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  save_to_file: true
  log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"